[package]
name = "HttpVisualizer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fltk = "1.4.2"
reqwest = { version = "0.11.17", features = ["blocking"] }
