#ifndef REQUEST_H
#define REQUEST_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

const char *Request(const char *url);

void FreeRequest(const char *ptr);

#ifdef __cplusplus
} // extern "C"
#endif // __cplusplus

#endif /* REQUEST_H */
