[package]
name = "Request"
version = "0.1.0"
edition = "2021"

[lib]
name = "request"
crate-type = ["staticlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.11.17", features = ["blocking"] }
